common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *common
  database: cycl_development

test:
  <<: *common
  database: cycl_test

staging:
  <<: *common
  database: cycl_staging

production:
  <<: *common
  database: cycl_production
